[tool.poetry]
name = "oleg"
version = "0.1.0"
description = ""
authors = ["stefanlight <steffmukhin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
hikari = "^2.0.0.dev121"
hikari-crescent = "^0.6.4"
hikari-miru = "^3.2.2"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
